### ISSUE TITLE
sample data Survey.csv

### ISSUE THREAD

**Issue by cara-shi** [mfumagalli68/A-Biterm-Topic-Model-for-Short-Texts#1]
I'm quite interested in BTM.
Can you show the sample data Survey.csv for testing? Thanks!

**Comment by mfumagalli68** [comment]
Hi. I can't share data since they are corporate data. I must add that you are Free to review my code: i've never had the time to check if everything I wrote was ok.

**Comment by cara-shi** [comment]
Thanks for reply.
Would you mind showing the format of sample data？ Thanks.

**Comment by mfumagalli68** [comment]
A simple R dataframe with one column and rows are the short text you want to extract your topics from.
